steps:
  - name: bash
    args:
      - ln
      - '-s'
      - ./slack/Dockerfile
      - ./Dockerfile
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/${PROJECT_ID}/cloud-build-notifier:${BRANCH_NAME}_${SHORT_SHA}'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - 'gcr.io/${PROJECT_ID}/cloud-build-notifier:${BRANCH_NAME}_${SHORT_SHA}'
      - 'gcr.io/${PROJECT_ID}/cloud-build-notifier:latest'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/cloud-build-notifier:latest'
  # setup.sh slack cloudbuild-notification.yaml cloud-build-slack-notification
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'slack-notifier'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/cloud-build-notifier:latest
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
images:
  - gcr.io/$PROJECT_ID/cloud-build-notifier

